### ISSUE TITLE
Cannot verify bot's sessions which leads to unencrypted exchanges

### ISSUE THREAD

**Issue by vincowl** [mautrix/signal#159] opened 2021-11-08 15:07 UTC
I enabled the double puppeting and messages sent by a standard signal account (on phone for instance) always appear as unverified session (bot's one). In the bot's chatroom where my user's log to the bot, bot's sessions are unverified too and the classical manual verification process is waiting an action from the bot's session.

How do I have to process to have bot's handled sessions fully verified ?

**Comment by vincowl** [comment] 2021-11-09 10:04
Seems to relate to #122

**Comment by tulir** [comment] 2021-11-09 10:29
Lack of verification doesn't lead to unencrypted exchanges, and yeah duplicate of #122

**Closed by tulir** 2021-11-09 10:29 UTC
