### ISSUE TITLE
Identity failure occurred while sending message to xxx

### ISSUE THREAD

**Issue by floviolleau** [mautrix/signal#148] opened 2021-10-25 08:33 UTC
Hi,

I have several issues when sending messages from Matrix

⚠ Your message was not bridged: Identity failure occurred while sending message to +<redacted>. New identity: <redacted>
Identity failure occurred while sending message to +<redacted>. New identity: <redacted>
Unregistered failure occurred while sending message to +<redacted>.
Identity failure occurred while sending message to +<redacted>. New identity: <redacted>

Any ideas how to fix it?
Thanks!

**Comment by jakecoppinger** [comment] 2021-11-11 03:17
Happened to me when a contact got a new phone and changed their safety number.

I marked as verified in Signal and now _i think_ it's working (messages go from Signal chat to Matrix, not sure of other way around).

Help message and error message didn't say what to do.

**Comment by floviolleau** [comment] 2021-11-12 10:02
Hi,

I did what @jakecoppinger made and waiting an incoming message to confirm.

Thanks!

**Comment by sumnerevans** [comment] 2022-01-05 14:53
Use the `mark-trusted` command to trust the new identity.

**Closed by sumnerevans** 2022-01-05 14:53 UTC

**Comment by mulles** [comment] 2022-01-05 15:29
Thx for the quick reply. I have no other device linked to signal, expect the signal bridge. Is their a way to get the safety number, to use the mark-trusted command.

**Comment by jzacsh** [comment] 2022-03-02 22:21
@sumnerevans might I suggest re-opening this bug and marking it fix once your tip is embedded in the failure message? eg:

> If you've added a new device, fix this by marking the new device trusted by messaging your signal bot with `mark-trusted`

**Comment by jzacsh** [comment] 2022-03-02 22:24
Oh actually maybe we're sharing messages (errors pasted in this bug) about the same error message but with different symptoms? For example in my case I get the [same message linked above](#issuecomment-1005704493) when I try to message in an existing group chat, but I'm getting it because I added a new **element/matrix** login. That is: I previously had a phone and a laptop logged into matrix, and now I have a phone and **two** laptops logged in. Does this sound plausible? Or am I misdiagnosing where this error message is coming from? If this is indeed the cause of the error, it doesn't seem like `mark-trusted` applies (I'm not sure what args I'd pass).
