### ISSUE TITLE
Failed to initialize database error

### ISSUE THREAD

**Issue by pbek** [mautrix/signal#406] opened 2024-01-01 13:50 UTC
After (docker) updating my bridge yesterday, it wasn't able to start anymore.

I pinned the issue down to this:

```
2023-12-31T21:44:30Z FTL Failed to initialize database error="failed to run upgrade #15: pq: insert or update on table \"reaction\" violates foreign key constraint \"reaction_message_fkey\"" db_section=main pq_error=
```

The new key `reaction_message_fkey` from https://github.com/mautrix/signal/blob/main/database/upgrades/16-refactor-postgres.sql didn't seem to go well with the already existing data in table `message`.

I needed to hunt down and delete "not aligning rows" in the table `messages` until the DB migration was able to run through, and the bridge was able to start again.

**Comment by tulir** [comment] 2024-01-01 14:08
Probably duplicate of #405

**Closed by tulir** 2024-01-01 14:08 UTC
Labels: bug

**Comment by pbek** [comment] 2024-01-01 14:31
Haha, we opened our issues at the same time! 😁 
Thank you!
