### ISSUE TITLE
Registration fails 

### ISSUE THREAD

**Issue by Boostflow** [mautrix/signal#49] opened 2021-01-27 20:15 UTC
<img width="1079" alt="image" src="https://user-images.githubusercontent.com/18465315/106054473-5fc18b00-60ec-11eb-96e0-9118419561d5.png">

Full trace:
```
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/mautrix/bridge/commands/handler.py", line 405, in handle
    await self._run_handler(handler, evt)
  File "/usr/lib/python3.8/site-packages/mautrix_signal/commands/auth.py", line 97, in enter_register_code
    account = await evt.bridge.signal.verify(username, code=evt.args[0])
  File "/opt/mautrix-signal/mausignald/signald.py", line 109, in verify
    resp = await self.request("verify", "verification_succeeded", username=username, code=code)
  File "/opt/mautrix-signal/mausignald/rpc.py", line 198, in request
    resp_type, resp_data = await self._raw_request(command, **data)
  File "/opt/mautrix-signal/mausignald/rpc.py", line 195, in _raw_request
    return await future
mausignald.errors.UnexpectedError: Bad response: 400 
```

As others mentioned I was already registered on signal in my phone, but I'd love to be able to uninstall it from there and keep only the matrix version. Any tips / feedback?

Version: mautrix-signal 0.1.0b2+dev.3852c137

**Comment by theCalcaholic** [comment] 2021-01-30 12:19
Duplicate of #39

**Closed** 2022-03-12 17:04 UTC
