### ISSUE TITLE
Upload not possible

### ISSUE THREAD

**Issue by xundeenergie** [mautrix/signal#565] opened 2024-10-19 19:03 UTC
Since a few days i get an error, when i try to post an image to a signal group via mautrix-signal.

I have upgraded Mautrix signal bridge to test if it works with current version:
```
# ./mautrix-signal --version
mautrix-signal 0.7.2 (built at Wed, 16 Oct 2024 11:03:04 +0000 with go1.23.2)
```
But it's the same.

Log:

```
Oct 19 20:44:57 sc-chat-01 mautrix_signal_primary[288808]: 2024-10-19T20:44:57.515+02:00 DBG received HTTP response action="send HTTP request" event_id=#########event_id############## event_loop_index=1 event_type=m.room.message login_id=839f18bc-0396-4321-b61a-6aab7aff4fc6 method=GET portal_id=#####portalid######/xJvQc= portal_mxid=######mxid#######:schuerz.at request_number=7 sender=@jakob:schuerz.at status_code=404 url=https://chat.signal.org/v3/attachments/form/upload
Oct 19 20:44:57 sc-chat-01 mautrix_signal_primary[288808]: 2024-10-19T20:44:57.521+02:00 DBG unexpected status code action="handle matrix event" body="{\"code\":404,\"message\":\"HTTP 404 Not Found\"}" event_id=#########event_id############## event_loop_index=1 event_type=m.room.message login_id=839f18bc-0396-4321-b61a-6aab7aff4fc6 portal_id=#####portalid######/xJvQc= portal_mxid=######mxid#######:schuerz.at sender=@jakob:schuerz.at status_code=404
Oct 19 20:44:57 sc-chat-01 mautrix_signal_primary[288808]: 2024-10-19T20:44:57.521+02:00 ERR Error decoding response body fetching upload attributes error="Unexpected status code: 404 404 Not Found" action="handle matrix event" event_id=#########event_id############## event_loop_index=1 event_type=m.room.message func="upload attachment" login_id=839f18bc-0396-4321-b61a-6aab7aff4fc6 portal_id=#####portalid######/xJvQc= portal_mxid=######mxid#######:schuerz.at sender=@jakob:schuerz.at
Oct 19 20:44:57 sc-chat-01 mautrix_signal_primary[288808]: 2024-10-19T20:44:57.522+02:00 ERR Failed to upload file error="Unexpected status code: 404 404 Not Found" action="handle matrix event" event_id=#########event_id############## event_loop_index=1 event_type=m.room.message login_id=839f18bc-0396-4321-b61a-6aab7aff4fc6 portal_id=#####portalid######/xJvQc= portal_mxid=#####mxid#######:schuerz.at sender=@jakob:schuerz.at
Oct 19 20:44:57 sc-chat-01 mautrix_signal_primary[288808]: 2024-10-19T20:44:57.524+02:00 ERR Failed to handle Matrix message error="failed to convert attachment: failed to reupload media: Unexpected status code: 404 404 Not Found" action="handle matrix event" event_id=#########event_id############## event_loop_index=1 event_type=m.room.message login_id=839f18bc-0396-4321-b61a-6aab7aff4fc6 portal_id=#####portalid######/xJvQc= portal_mxid=######mxid#######:schuerz.at sender=@jakob:schuerz.at
Oct 19 20:44:57 sc-chat-01 mautrix_signal_primary[288808]: 2024-10-19T20:44:57.745+02:00 DBG Request completed action="handle matrix event" duration=208.035243 event_id=#########event_id############## event_loop_index=1 event_type=m.room.message login_id=839f18bc-0396-4321-b61a-6aab7aff4fc6 method=PUT portal_id=############portalid########### portal_mxid=!jVBFrteFsvGXzYkdvT:schuerz.at req_body={"body":"⚠️ Your message was not bridged: failed to reupload media","m.mentions":{"user_ids":["@jakob:schuerz.at"]},"m.relates_to":{"m.in_reply_to":{"event_id":"#########event_id##############"}},"msgtype":"m.text"} req_id=8 response_length=59 response_mime=application/json sender=@jakob:schuerz.at status_code=200 url=http://localhost:8008/_matrix/client/v3/rooms/%21jVBFrteFsvGXzYkdvT:schuerz.at/send/m.room.message/mautrix-go_1729363497537634003_2?user_id=%40signalbotprimary%3Aschuerz.at

```
Seems, signal changed the upload url. When i try to open https://chat.signal.org/v3/attachments/form/upload from the error i get a certificate-warning and this:

`{"code":404,"message":"HTTP 404 Not Found"}`

**Comment by tulir** [comment] 2024-10-19 19:14
Duplicate of #564

**Closed by tulir** 2024-10-19 19:14 UTC
Labels: bug
