### ISSUE TITLE
Uploading attachments returns 404

### ISSUE THREAD

**Issue by TheBlueMatt** [mautrix/signal#567] opened 2024-11-05 01:32 UTC
Was happening on 0.6.2 but upgraded to 0.7.2 and I still see it. I think the media is unauthenticated cause I can fetch it without auth (is that what unauthenticated media is?).

```
Nov 05 01:23:11 signal-puppet mautrix-signal[101699]: 2024-11-05T01:23:11.186Z DBG Request completed action="handle matrix event" duration=2.250113 event_id=$XXX event_loop_index=1 event_type=m.room.message login_id=YYY method=GET portal_id=ZZZ portal_mxid=!NNN req_id=513 response_length=-1 response_mime=image/png sender=@user status_code=200 url=path_to_matrix_file
Nov 05 01:23:11 signal-puppet mautrix-signal[101699]: 2024-11-05T01:23:11.294Z DBG received HTTP response action="send HTTP request" event_id=$XXX event_loop_index=1 event_type=m.room.message login_id=YYY method=GET portal_id=ZZZ portal_mxid=!NNN:bitcoin.ninja request_number=4 sender=@user status_code=404 url=https://chat.signal.org/v3/attachments/form/upload
Nov 05 01:23:11 signal-puppet mautrix-signal[101699]: 2024-11-05T01:23:11.294Z DBG unexpected status code action="handle matrix event" body="{\"code\":404,\"message\":\"HTTP 404 Not Found\"}" event_id=$XXX event_loop_index=1 event_type=m.room.message login_id=YYY portal_id=ZZZ portal_mxid=!NNN sender=@user status_code=404
Nov 05 01:23:11 signal-puppet mautrix-signal[101699]: 2024-11-05T01:23:11.294Z ERR Error decoding response body fetching upload attributes error="Unexpected status code: 404 404 Not Found" action="handle matrix event" event_id=$XXX event_loop_index=1 event_type=m.room.message func="upload attachment" login_id=YYY portal_id=ZZZ portal_mxid=!NNN sender=@user
Nov 05 01:23:11 signal-puppet mautrix-signal[101699]: 2024-11-05T01:23:11.294Z ERR Failed to upload file error="Unexpected status code: 404 404 Not Found" action="handle matrix event" event_id=$XXX event_loop_index=1 event_type=m.room.message login_id=YYY portal_id=ZZZ portal_mxid=!NNN sender=@user
Nov 05 01:23:11 signal-puppet mautrix-signal[101699]: 2024-11-05T01:23:11.294Z ERR Failed to handle Matrix message error="failed to convert attachment: failed to reupload media: Unexpected status code: 404 404 Not Found" action="handle matrix event" event_id=$XXX event_loop_index=1 event_type=m.room.message login_id=YYY portal_id=ZZZ portal_mxid=!NNN sender=@user
```

**Comment by tulir** [comment] 2024-11-05 07:58
Duplicate of #564

**Closed by tulir** 2024-11-05 07:58 UTC
Labels: bug
