### ISSUE TITLE
Wrong user names in rooms

### ISSUE THREAD

**Issue by Fobhep** [mautrix/signal#368] opened 2023-06-15 19:29 UTC
Sometimes users in a room that are not part of my contact list, will be assigned randomly with names from people of my contacts by matrix/signal bridge.
Eg a person that would be called "Max" but is not in my contact list will be given the name "Steven Miller" - later is an entry from my contacts.
It does not happen with all users that are in signal rooms - only with some and I can't find a pattern.
By contact list I mean my actual phone contacts.

Does anybody have an idea how to fix this?

**Comment by tulir** [comment] 2023-06-15 19:33
Duplicate of #343 (but it's a signald bug and probably won't be fixed)

**Closed by tulir** 2023-06-15 19:33 UTC
Labels: bug
