### ISSUE TITLE
Configuration option to only manually open signal rooms/dms

### ISSUE THREAD

**Issue by jakobw123** [mautrix/signal#469] opened 2024-03-02 16:26 UTC
I've been playing around with a Matrix Homeserver setup lately, via the [Matrix Docker Ansible Deploy](https://github.com/spantaleev/matrix-docker-ansible-deploy) bundle. As this is my first project regarding the Matrix world, i'm fairly new to the topic.
I've also added some features such as this [Signal Bridge](https://github.com/mautrix/signal) as well as the [WhatsApp Bridge](https://github.com/mautrix/whatsapp).
I would like to be able to **only manually sync rooms/dms** between other ecosystems, like Signal, WhatsApp, and Matrix.
For WhatsApp i've been able to achieve this by turning off the backfill and making use of the `open <room id>` command. Room ids can be accessed with the `list <contacts/groups>` command.

I would like to configure my Signal Bridge in similar way. Unfortunately, i couldn't find any commands to manually sync/open rooms/dms from Signal to Matrix. 
- Have i missed any commands already available, which achieve manual room openings?
- If not, are there any plans to add those type of features to newer versions of this Signal Bridge?
- Or does anyone added such features to their own project and could give me a short hint on how to add those to my project?

In addition i would like to prevent the Signal Bridge from syncing rooms with Matrix when new messages are received in the signal-sided room (after linking my Signal account with the Signal Bridge Bot).
- Are there any settings currently available to prevent auto sync on incoming message events?

**Comment by tulir** [comment] 2024-08-17 18:22
Duplicate of #254

**Closed by tulir** 2024-08-17 18:22 UTC
Labels: enhancement
