### ISSUE TITLE
When I reply to a message, on the signal side an almost useless reference matrix.to URL is given, there is no reply logic, and the reply is not separated with a newline from the quoted message

### ISSUE THREAD

**Issue by dreirund** [mautrix/signal#523] opened 2024-07-11 13:55 UTC
I use mautrix-signal version 0.6.2 as [installed on yatrix.org](https://yatrix.org/wissen/anleitungen/bruecken/) in double pupetting mode.

When I reply to a message, on the signal side an almost useless reference matrix.to URL is given, the reply does not appear as a real reply, and the reply is not separated with a newline from the quoted message:

Here is a screenshot the message with the reply as written in the Matrix client:  
<hr>

![01_-_reply-matrix](https://github.com/mautrix/signal/assets/1590519/c4591b12-55b4-456e-8968-31894ffdf170)  
<hr>

Ans here is how it appears on the Signal side:  
<hr>

![02_-_reply-signal](https://github.com/mautrix/signal/assets/1590519/a664ddce-da89-42e1-8fb4-6d877d443f92)  
<hr>

When I instead reply in thread on the Matrix side, on the Signal side the message appears as a standalone new message:  
<hr>

![02_-_reply-thread-signal](https://github.com/mautrix/signal/assets/1590519/06a7ed30-92cd-4608-8bcc-1e39fd959250)  
<hr>

When I remove the thread on Matrix side (by removing the "parent" message of the thread, which deletes the whole thread), on Signal side the reply is still present:  
<hr>

![04_-_thread-deleted-signal](https://github.com/mautrix/signal/assets/1590519/99b62a1c-4587-4b6e-9391-ddb15a18c7c3)  
<hr>

Regards!

**Comment by tulir** [comment] 2024-07-11 13:56
Duplicate of #519

**Closed by tulir** 2024-07-11 13:56 UTC
Labels: bug
